USE [master]
GO

/****** Object:  Database [LocateSupport]    Script Date: 4/18/2019 1:21:56 PM ******/
CREATE DATABASE [LocateSupport]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LocateSupport', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\LocateSupport.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LocateSupport_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\LocateSupport_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LocateSupport] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LocateSupport].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LocateSupport] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LocateSupport] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LocateSupport] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LocateSupport] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LocateSupport] SET ARITHABORT OFF 
GO

ALTER DATABASE [LocateSupport] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LocateSupport] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [LocateSupport] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LocateSupport] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LocateSupport] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LocateSupport] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LocateSupport] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LocateSupport] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LocateSupport] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LocateSupport] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LocateSupport] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LocateSupport] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LocateSupport] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LocateSupport] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LocateSupport] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LocateSupport] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LocateSupport] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LocateSupport] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LocateSupport] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LocateSupport] SET  MULTI_USER 
GO

ALTER DATABASE [LocateSupport] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LocateSupport] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LocateSupport] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LocateSupport] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LocateSupport] SET  READ_WRITE 
GO


